version: '3'

services:
  mongo_db:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=crude_nest
    volumes:
      - ./mgdata:/data/db

  app:
    build: .
    container_name: node
    restart: always
    image: nest
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - mongo_db
